/**
 * Converts the web pig sprite into a form React Native can draw.
 *
 * The web renders each pig as one CSS `box-shadow` with ~571 shadow entries —
 * elegant there, impossible here. This reads that same source of truth and
 * emits horizontal run-length rectangles, so the phone draws ~150 views per
 * pig instead of 571, and the two platforms can never drift apart because the
 * sprite is generated from the web file rather than redrawn.
 *
 *   pnpm gen:pig
 */
import { readFileSync, writeFileSync } from "node:fs";

const SOURCE = "src/components/pigPixels.ts";
const OUT = "mobile/src/components/pigPixels.ts";

/** Maps each web colour expression onto a named tone the RN side resolves. */
const TONE: Record<string, string> = {
  "var(--pig-line)": "line",
  "var(--pig-ear)": "ear",
  "var(--pig-body)": "body",
  "var(--pig-nose)": "nose",
  "color-mix(in srgb, var(--pig-ear) 88%, black)": "earShade",
  "color-mix(in srgb, var(--pig-ear) 65%, white)": "earLight",
  "color-mix(in srgb, var(--pig-body) 88%, black)": "bodyShade",
  "color-mix(in srgb, var(--pig-body) 65%, white)": "bodyLight",
  "color-mix(in srgb, var(--pig-nose) 90%, black)": "noseShade",
};

const src = readFileSync(SOURCE, "utf8");

const cell = Number(/PIXEL_CELL = (\d+)/.exec(src)?.[1] ?? 4);
const cols = Number(/PIXEL_COLS = (\d+)/.exec(src)?.[1] ?? 32);
const rows = Number(/PIXEL_ROWS = (\d+)/.exec(src)?.[1] ?? 32);

const states = [...src.matchAll(/^ {2}(\w+): `([\s\S]*?)`,$/gm)];
if (states.length === 0) throw new Error("no pig states found — did pigPixels.ts change shape?");

/**
 * One `<x>px <y>px 0 <colour>` entry.
 *
 * The colour alternatives must be spelled out: `color-mix(...)` contains a
 * nested `var(...)`, so a lazy `[^)]*\)` stops at the inner bracket and
 * silently truncates every mixed tone.
 */
const ENTRY =
  /(-?\d+)px\s+(-?\d+)px\s+0\s+(color-mix\(in srgb,\s*var\(--pig-\w+\)\s*\d+%,\s*\w+\)|var\(--pig-\w+\))/g;

const out: string[] = [];
for (const [, state, block] of states) {
  const pixels: { x: number; y: number; tone: string }[] = [];
  for (const [, px, py, colour] of block.matchAll(ENTRY)) {
    const tone = TONE[colour.replace(/\s+/g, " ").trim()];
    if (!tone) throw new Error(`unmapped colour in ${state}: ${colour}`);
    pixels.push({ x: Number(px) / cell, y: Number(py) / cell, tone });
  }

  // Merge runs left-to-right within a row. Sorting by row then column is what
  // makes adjacency detectable at all.
  pixels.sort((a, b) => a.y - b.y || a.x - b.x);
  const rects: [number, number, number, string][] = [];
  for (const p of pixels) {
    const last = rects[rects.length - 1];
    if (last && last[1] === p.y && last[3] === p.tone && last[0] + last[2] === p.x) {
      last[2] += 1;
    } else {
      rects.push([p.x, p.y, 1, p.tone]);
    }
  }
  out.push(
    `  ${state}: [\n${rects.map((r) => `    [${r[0]},${r[1]},${r[2]},"${r[3]}"]`).join(",\n")},\n  ],`,
  );
  console.log(`${state}: ${pixels.length} pixels -> ${rects.length} rects`);
}

writeFileSync(
  OUT,
  `/**
 * GENERATED by scripts/gen-pig-pixels.ts — do not edit.
 *
 * Run-length rectangles derived from the web sprite in
 * src/components/pigPixels.ts, so both platforms draw the same pig.
 * Each rect is [x, y, width, tone] in grid cells.
 */

export const PIXEL_COLS = ${cols};
export const PIXEL_ROWS = ${rows};

export type PigTone =
${[...new Set(Object.values(TONE))].map((t) => `  | "${t}"`).join("\n")};

export type PigRect = [number, number, number, PigTone];

export const PIG_RECTS: Record<string, PigRect[]> = {
${out.join("\n")}
};
`,
);
console.log(`wrote ${OUT}`);
