/**
 * Converts the cow and raccoon sprites into a form React Native can draw.
 *
 * The pig sprite uses CSS custom properties, so `gen-pig-pixels.ts` maps
 * `var(--pig-body)` straight onto a tone name. Cow and raccoon instead bake
 * one coat's literal hex into the pixel data and swap colours at render, so
 * this reads that default coat out of the component and inverts it: every hex
 * becomes the tone it stands for, and the phone recolours from there.
 *
 *   pnpm gen:animals
 */
import { readFileSync, writeFileSync } from "node:fs";

interface Animal {
  name: "cow" | "raccoon";
  pixels: string;
  component: string;
  /** The coat the literal hex values were generated from. */
  defaultCoat: string;
  out: string;
}

const ANIMALS: Animal[] = [
  {
    name: "cow",
    pixels: "src/components/cowPixels.ts",
    component: "src/components/Cow.tsx",
    defaultCoat: "sky",
    out: "mobile/src/components/cowPixels.ts",
  },
  {
    name: "raccoon",
    pixels: "src/components/raccoonPixels.ts",
    component: "src/components/Raccoon.tsx",
    defaultCoat: "slate",
    out: "mobile/src/components/raccoonPixels.ts",
  },
];

/** Pulls `{ body: "#FFFFFF", shade: "#DBE6F5", ... }` out of the component. */
function readCoat(file: string, coat: string): Record<string, string> {
  const src = readFileSync(file, "utf8");
  const line = new RegExp(`${coat}:\\s*\\{([^}]*)\\}`).exec(src);
  if (!line) throw new Error(`no ${coat} coat in ${file}`);
  const out: Record<string, string> = {};
  for (const [, tone, hex] of line[1].matchAll(/(\w+):\s*"(#[0-9A-Fa-f]{6})"/g)) {
    out[tone] = hex.toLowerCase();
  }
  return out;
}

for (const animal of ANIMALS) {
  const src = readFileSync(animal.pixels, "utf8");
  const coat = readCoat(animal.component, animal.defaultCoat);
  // Inverted so a hex from the sprite resolves to the tone it represents.
  const byHex = new Map(Object.entries(coat).map(([tone, hex]) => [hex, tone]));

  const cell = Number(/PIXEL_CELL = (\d+)/.exec(src)?.[1] ?? 4);
  const cols = Number(/PIXEL_COLS = (\d+)/.exec(src)?.[1] ?? 22);
  const rows = Number(/PIXEL_ROWS = (\d+)/.exec(src)?.[1] ?? 26);

  const states = [...src.matchAll(/^ {2}(\w+):\s*"([^"]*)",?$/gm)];
  if (states.length === 0) throw new Error(`no states found in ${animal.pixels}`);

  const unknown = new Set<string>();
  const blocks: string[] = [];

  for (const [, state, block] of states) {
    const pixels: { x: number; y: number; tone: string }[] = [];
    for (const [, px, py, hex] of block.matchAll(
      /(-?\d+)px\s+(-?\d+)px\s+(#[0-9A-Fa-f]{6})/g,
    )) {
      // A hex absent from the coat is a fixed detail — hooves, eye whites —
      // that shouldn't recolour with the coat, so it passes through literally
      // and the renderer uses it as-is.
      const tone = byHex.get(hex.toLowerCase()) ?? hex.toLowerCase();
      if (!byHex.has(hex.toLowerCase())) unknown.add(hex.toLowerCase());
      pixels.push({ x: Number(px) / cell, y: Number(py) / cell, tone });
    }

    // Merge runs left-to-right within a row, same as the pig generator.
    pixels.sort((a, b) => a.y - b.y || a.x - b.x);
    const rects: [number, number, number, string][] = [];
    for (const p of pixels) {
      const last = rects[rects.length - 1];
      if (last && last[1] === p.y && last[3] === p.tone && last[0] + last[2] === p.x) last[2] += 1;
      else rects.push([p.x, p.y, 1, p.tone]);
    }
    blocks.push(
      `  ${state}: [\n${rects.map((r) => `    [${r[0]},${r[1]},${r[2]},"${r[3]}"]`).join(",\n")},\n  ],`,
    );
    console.log(`${animal.name}/${state}: ${pixels.length} pixels -> ${rects.length} rects`);
  }

  if (unknown.size > 0) {
    console.log(`  ${animal.name}: ${unknown.size} fixed colour(s): ${[...unknown].join(", ")}`);
  }

  const tones = [...new Set(Object.keys(coat))];
  writeFileSync(
    animal.out,
    `/**
 * GENERATED by scripts/gen-animal-pixels.ts — do not edit.
 *
 * Run-length rectangles derived from ${animal.pixels}, so both platforms draw
 * the same ${animal.name}. Each rect is [x, y, width, tone] in grid cells.
 */

export const PIXEL_COLS = ${cols};
export const PIXEL_ROWS = ${rows};

/** A coat tone, or a literal hex for details that never recolour. */
export type ${animal.name === "cow" ? "Cow" : "Raccoon"}Tone =
${tones.map((t) => `  | "${t}"`).join("\n")}
  | (string & {});

export type ${animal.name === "cow" ? "Cow" : "Raccoon"}Rect = [
  number,
  number,
  number,
  ${animal.name === "cow" ? "Cow" : "Raccoon"}Tone,
];

export const ${animal.name.toUpperCase()}_RECTS: Record<
  string,
  ${animal.name === "cow" ? "Cow" : "Raccoon"}Rect[]
> = {
${blocks.join("\n")}
};
`,
  );
  console.log(`wrote ${animal.out}`);
}
